### ISSUE TITLE
When generate schedule, it redirect to login page (But already logged in with a line.)

### ISSUE THREAD

**Issue by SeventwoZ** [Aquaholic-ISP/Aquaholic#41]
![image](https://user-images.githubusercontent.com/91252217/203497646-527df4e0-3ee5-429a-b494-2dc10394c370.png)
![image](https://user-images.githubusercontent.com/91252217/203497666-27f89a4f-f182-4062-ab8d-268b828b3069.png)

**Comment by Siripa-Maneein** [comment]
This is not a functionality defect actually as it is the link to let visitor give permission to line notification in case user does not have notify token yet. However, we understand that it can be quite unclear because user doesn't know what it does so we add a page to inform user to login to line notify first in this commit e0ddd90d4607d2943d63721368e8474b69d2b9e3.

**Comment by Siripa-Maneein** [comment]
Thank you.
